config/routes.rb
KarateJournal::Application.routes.draw do
  resources :entries do
    collection do
      get :search
    end
  end

  root 'entries#index'
end

app/models/concerns/entry_search.rb
module EntrySearch

  def search(search_terms)
    result_hash = {}

    search_terms.each do |term|
      # Search for term in source
      entries = Entry.where('source like ?', "%#{term}%")
      result_hash = add_entries_to_search_results(result_hash, entries, 'source', term, 100)

      # Search for term in title
      entries = Entry.where('title like ?', "%#{term}%")
      result_hash = add_entries_to_search_results(result_hash, entries, 'title', term, 75)

      # Search for term in body
      entries = Entry.where('body like ?', "%#{term}%")
      result_hash = add_entries_to_search_results(result_hash, entries, 'body', term, 5)
    end

    result_hash.sort { |a,b| b[1] <=> a[1] }.map { |x| x[0] }
  end

  private

  def add_entries_to_search_results(results, entries, field, term, points)
    entries.each do |entry|
      if results[entry].nil?
        results[entry] = points * count_occurrences(term, entry[field])
      else
        results[entry] = results[entry] + (points * count_occurrences(term, entry[field]))
      end
    end
    results
  end

  def count_occurrences(word, paragraph)
    count = 0
    paragraph.split(" ") do |pword|
      count = count + 1 if pword.upcase.tr('. ', '') == word.upcase
    end
    count
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  extend EntrySearch

  has_one :entry_type

  scope :by_type, ->(entry_type) { where(entry_type_id: entry_type) }
  scope :ordered_by_title, -> { order('title') }
  scope :ordered_by_date, -> { order('created_at') }

  validates :title, presence: true
  validates :body, presence: true

  def body_without_fragment_links
    body.gsub(/<lfrag [^>]+>/, "").gsub("</lfrag>", "").
         gsub(/<bfrag [^>]+>/, "").gsub("</bfrag>", "")
  end

  def line_fragments
    fragments("lfrag")
  end

  def body_fragments
    fragments("bfrag")
  end

  private

  # This is without a doubt the worst performing implementation of this method.
  # But it works, and it works well with my small database.  Saving any sort
  # of optimizations for a later date.
  def fragments(fragment_type)
    frags = []
    fragment_regex = fragment_regex(fragment_type)

    Entry.where("body like ?", "%#{self.title}%").each do |entry|
      text = entry.body.gsub("\r\n", "[newline]")
      while text =~ fragment_regex
        fragment = $1.strip.gsub("[newline]", "\r\n")
        frags << { source: entry, fragment: fragment }
        text = text.sub(fragment_regex, "")
      end
    end

    frags.sort { |a,b| b[:source].created_at <=> a[:source].created_at }
  end

  def fragment_regex(fragment_type)
    /<#{fragment_type} [^>]+#{self.title}[^>]*>([^<]+)<\/#{fragment_type}>/
  end

end

app/models/entry_type.rb
class EntryType < ActiveRecord::Base

  validates :description, presence: true

  private

  def self.method_missing(method, *args)
    self.entry_types[method.to_s] || super
  end

  def self.entry_types
    @entry_types ||= Hash[*EntryType.all.map { |x| [x.description.upcase.gsub(' ', '_'), x] }.flatten]
  end

end

app/controllers/application.rb
require 'app_config'

class ApplicationController < ActionController::Base

  htpasswd_file = AppConfig.instance.htpasswd_file
  htpasswd :file => htpasswd_file unless htpasswd_file.blank?

  session :session_key => '_karate-journal_session_id'
  layout 'standard'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate

  private

  def authenticate
    if Rails.env.production?
      username = ApplicationConfig.username
      password = ApplicationConfig.password

      if username.present? && password.present?
        authenticate_or_request_with_http_basic("KarateJournal") do |http_username, http_password|
          http_username == username && http_password == password
        end
      end
    end
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_filter :load_entry, only: [:show, :edit, :update, :destroy]

  def index
    @kihon_entries            = Entry.by_type(EntryType.KIHON).ordered_by_title
    @kata_entries             = Entry.by_type(EntryType.KATA).ordered_by_title
    @kumite_entries           = Entry.by_type(EntryType.KUMITE).ordered_by_title
    @drill_entries            = Entry.by_type(EntryType.DRILL).ordered_by_title
    @other_entries            = Entry.by_type(EntryType.OTHER).ordered_by_title
    @senior_visit_entries     = Entry.by_type(EntryType.SENIOR_VISIT).ordered_by_date
    @special_training_entries = Entry.by_type(EntryType.SPECIAL_TRAINING).ordered_by_date
    @experience_entries       = Entry.by_type(EntryType.EXPERIENCE).ordered_by_date
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to entry_path(@entry)
    else
      logger.error "Create entry failed: #{@entry.errors.full_messages}"
      render action: 'new'
    end
  end

  def edit
  end

  def update
    @entry.attributes = entry_params
    if @entry.save
      redirect_to entry_path(@entry)
    else
      logger.error "Edit entry failed: #{@entry.errors.full_messages}"
      render action: 'edit'
    end
  end

  def destroy
    @entry.destroy
    redirect_to root_path
  end

  def search
    @query = params[:query]
    @search_terms = @query.split(' ')
    @results = Entry.search(@search_terms)
  end

  private

  def load_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:title, :body, :source, :entry_type_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
require 'rdoc/markup'
require 'rdoc/markup/to_html'

module EntriesHelper

  def markup(text)
    p = RDoc::Markup.new
    h = RDoc::Markup::ToHtml.new
    p.convert(text, h).html_safe
  end

  def display_search_result_body(search_terms, body, source)
    body = trim_search_result_body(search_terms, body, source)
    body = highlight_search_terms(search_terms, body)
    body.html_safe
  end

  private

  def trim_search_result_body(search_terms, body, source)
    pre_post_size = 30
    max_len = 500

    new_body = ""
    search_terms.each do |term|
      offset = body.upcase.index(term.upcase)
      while (!offset.nil?)
        if offset > pre_post_size
          new_body << "..."
          new_body << body.slice(offset - pre_post_size, term.size + (pre_post_size * 2))
        else
          new_body << body.slice(0, offset + term.size + pre_post_size)
        end

        new_body << "..."
        offset = body.upcase.index(term.upcase, offset + 1)
      end

      new_body << "Source: #{source}" if source.upcase.include?(term.upcase)
    end

    new_body.slice(0, max_len)
  end

  def highlight_search_terms(search_terms, body)
    search_terms.each do |term|
      regex = ""
      term.each_char { |char| regex << "[" + char.upcase + "|" + char.downcase + "]" }
      while body =~ /[^highlight">](#{regex})/
        body.gsub!($1, "<span class=\"highlight\">#{$1}</span>")
      end
    end
    body
  end

end

app/views/entries/_entries.html.erb
<table>
  <tbody>
    <%= entries.in_groups_of(4) do |entry_group| %>
      <tr>
        <% entry_group.compact.each do |entry| %>
          <td><%= link_to entry.title, entry_path(entry) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/entries/_entry_group.html.erb
<div class="section">
  <h2><%= group_name %></h2>
   <div class="section_content">
     <%= render partial: 'entries', locals: { entries: entries } %>
   </div>
</div>

app/views/entries/_form_entry.html.erb
<% if @entry.errors.any? %>
  <div id="errors">
    <% @entry.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %>

<p class="entry_field">
  <%= f.label :title, 'Description' %>
  <%= f.text_field :title, size: 80 %>
</p>

<p class="entry_field">
  <%= f.label :body, 'Entry Body' %>
  <%= f.text_area :body, cols: 80, rows: 20 %>
</p>

<p class="entry_field">
  <%= f.label :entry_type, 'Entry Type' %>
  <%= f.select :entry_type_id, EntryType.all.collect { |t| [ t.description, t.id ] }, {} %>
</p>

<p class="entry_field">
  <%= f.label :source, 'Source' %>
  <%= f.text_field :source  %></p>
</p>

app/views/entries/_fragments.html.erb
<h2>From Other Entries</h2>

<% entry.body_fragments.each do |fragment| %>
  From <%= link_to "#{fragment[:source].title}", entry_path(fragment[:source]) %>
  <div class='fragment'>
    <%= markup(fragment[:fragment]) %>
  </div>
<% end %>

<% if entry.line_fragments.any? %>
  <ul>
    <% entry.line_fragments.each do |fragment| %>
      <li>
        <%= markup(fragment[:fragment]).sub(/<\/p>$/, "").html_safe %> -
          <small><%= link_to "#{fragment[:source].title}", entry_path(fragment[:source]) %></small>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/entries/edit.html.erb
<h1>Edit entry</h1>

<%= form_for @entry do |f| %>
  <%= render partial: 'form_entry', locals: { f: f } %>
  <%= submit_tag 'Save' %>
<% end %>

<div id="actions">
  <%= link_to 'Show', entry_path(@entry) %> |
  <%= link_to 'Back', root_path %>
</div>

app/views/entries/index.html.erb
<%= link_to 'Create New Entry', new_entry_path, id: 'create_link' %>

<%= render partial: 'entry_group', locals: { group_name: "Kihon", entries: @kihon_entries } %>
<%= render partial: 'entry_group', locals: { group_name: "Kata", entries: @kata_entries } %>
<%= render partial: 'entry_group', locals: { group_name: "Kumite", entries: @kumite_entries } %>
<%= render partial: 'entry_group', locals: { group_name: "Drills", entries: @drill_entries } %>
<%= render partial: 'entry_group', locals: { group_name: "Senior Visits", entries: @senior_visit_entries } %>
<%= render partial: 'entry_group', locals: { group_name: "Special Training", entries: @special_training_entries } %>
<%= render partial: 'entry_group', locals: { group_name: "Experiences", entries: @experience_entries } %>

<% if @other_entries.any? %>
  <%= render partial: 'entry_group', locals: { group_name: "Other", entries: @other_entries } %>
<% end %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= form_for @entry do |f| %>
  <%= render partial: 'form_entry', locals: { f: f } %>
  <%= submit_tag 'Save' %>
<% end %>

<div id="actions">
  <%= link_to 'Back', root_path %>
</div>

app/views/entries/search.html.erb
<% if @results.empty? %>
   <div class="entry">
      <p>No search results found</p>
   </div>
<% else %>
   <% @results.each do |entry| %>
      <div class="entry">
         <strong><%= link_to(entry.title, entry_path(entry)) %></strong> -
         <%= display_search_result_body(@search_terms, entry.body, entry.source) %>
      </div>
   <% end -%>
<% end -%>

<div id="actions">
  <%= link_to 'Back', root_path %>
</div>

app/views/entries/show.html.erb
<div class="entry">
  <h2><%= h @entry.title %></h2>
  <hr />

  <%= markup(@entry.body_without_fragment_links) %>
  <hr />

  <% if @entry.body_fragments.any? || @entry.line_fragments.any? %>
    <%= render partial: 'fragments', locals: { entry: @entry } %>
  <% end %>

  <% if @entry.source.present? -%>
    <p><strong>Source: </strong><%= @entry.source %></p>
  <% end -%>
</div>

<div id="actions">
  <%= link_to 'Back', root_path %> |
  <%= link_to 'Edit', edit_entry_path(@entry) %> |
  <%= link_to 'Delete', entry_path(@entry), data: { confirm: 'Are you sure you would like to delete this entry?' }, :method => :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Karate Journal</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="header">
    <h1><%= link_to 'Karate Journal', root_path %></h1>
  </div>

  <div id="search_box">
    <%= form_tag search_entries_path, method: :get do %>
      <%= text_field_tag :query, @query %>
      <%= submit_tag "Search" %>
    <% end %>
  </div>

  <div id="content">
    <%= yield :layout %>
  </div>
</body>

</html>